---
title: "DM_data"
author: "EOL"
date: "2023-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# Load necessary libraries
library(ggplot2)
```

```{r}
met_path <- '/Users/emmaolsen/Library/CloudStorage/OneDrive-Aarhusuniversitet/cognitive_science/00_MS_cogsci/1_DM/exam23/data_MET.csv'
wm_path <- '/Users/emmaolsen/Library/CloudStorage/OneDrive-Aarhusuniversitet/cognitive_science/00_MS_cogsci/1_DM/exam23/data_DIGIT.csv'
```

```{r}
# Read the data from CSV file
met_data <- read.csv(met_path)
wm_data <- read.csv(wm_path)
```

## MET DATA
```{r}
# Enhanced plot for the distribution of MEL scores with a probability density curve
ggplot(met_data, aes(x=MEL)) +
  geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.9) + # Add density curve with fill
  geom_vline(aes(xintercept=mean(MEL, na.rm=TRUE)), color="red", linetype="dashed", size=1) + # Add mean line
  theme_minimal(base_size = 14) + # Base font size
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 12),
    legend.position = "none", # Remove legend if not necessary
    axis.line = element_line(color = "black", size = 0.5) # Add axis lines
  ) +
  ggtitle("Probability Density of MEL Scores") +
  xlab("MEL Score") +
  ylab("Probability Density") +
  scale_x_continuous(breaks=seq(min(met_data$MEL), max(met_data$MEL), by=1))
```

```{r}
# Distribution of MEL scores
ggplot(met_data, aes(x=MEL)) +
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) + # Adjust colors and transparency
  geom_vline(aes(xintercept=mean(MEL)), color="red", linetype="dashed", size=1) + # Add mean line
  theme_minimal(base_size = 14) + # Base font size
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 12),
    legend.position = "none" # Remove legend if not necessary
  ) +
  ggtitle("Distribution of MEL Scores") +
  xlab("MEL Score") +
  ylab("Frequency") +
  scale_x_continuous(breaks=seq(min(met_data$MEL), max(met_data$MEL), by=1))+
  geom_density()
```
```{r}
# Enhanced plot for the distribution of MEL scores
ggplot(met_data, aes(x=RYT)) +
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) + # Adjust colors and transparency
  geom_vline(aes(xintercept=mean(RYT)), color="red", linetype="dashed", size=1) + # Add mean line
  theme_minimal(base_size = 14) + # Base font size
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 12),
    legend.position = "none" # Remove legend if not necessary
  ) +
  ggtitle("Distribution of RYT Scores") +
  xlab("RYT Score") +
  ylab("Frequency") +
  scale_x_continuous(breaks=seq(min(met_data$MEL), max(met_data$MEL), by=1))+
  geom_density()
```
```{r}
# Enhanced plot for the distribution of RYT scores with a probability density curve
ggplot(met_data, aes(x=RYT)) +
  geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.9) + # Add density curve with fill
  geom_vline(aes(xintercept=mean(RYT, na.rm=TRUE)), color="red", linetype="dashed", size=1) + # Add mean line
  theme_minimal(base_size = 14) + # Base font size
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 12),
    legend.position = "none", # Remove legend if not necessary
    axis.line = element_line(color = "black", size = 0.5) # Add axis lines
  ) +
  ggtitle("Probability Density of RYT Scores") +
  xlab("RYT Score") +
  ylab("Probability Density") +
  scale_x_continuous(breaks=seq(min(met_data$MEL), max(met_data$MEL), by=1))

```

## WM Data

```{r}
wm_data$WM_score <- wm_data$Forfra+wm_data$Bagfra+wm_data$Rangordning
```

```{r}
# Distribution of WN scores
ggplot(wm_data, aes(x=WM_score)) +
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) + # Adjust colors and transparency
  geom_vline(aes(xintercept=mean(WM_score)), color="red", linetype="dashed", size=1) + # Add mean line
  theme_minimal(base_size = 14) + # Base font size
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 12),
    legend.position = "none" # Remove legend if not necessary
  ) +
  ggtitle("Distribution of WM Scores") +
  xlab("WM Score") +
  ylab("Frequency") +
  scale_x_continuous(breaks=seq(min(wm_data$WM_score), max(wm_data$WM_score), by=1))+
  geom_density()
```

